### ISSUE TITLE
Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by danielblues** [Piwigo/piwigo-gmaps#1]
I've got this error "Google Maps API error: MissingKeyMapError" but gmaps_api_key config is commented on the source. What's the best way to fix it, just uncomment it?

**Comment by danielblues** [comment]
It looks like something changed on 22nd June, "We no longer support keyless access "

https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update

**Comment by modus75** [comment]
It's not enough to uncomment those lines. They are there from 10 years ago
when a key was required.
I'll have to check the code and add everything back
