### ISSUE TITLE
World Map link does not work

### ISSUE THREAD

**Issue by javaboy79** [Piwigo/piwigo-gmaps#2]
The world map link from the home page does not work.  The link goes to <server>/map.php?/categories and this produces a php error because the page does not exist.  However, going to the following page does work:  <server>/plugins/rv_gmaps/map.php?/categories

**Comment by modus75** [comment]
Hello. This file is created by the plug-in on activation. Maybe permission issues or copying files around from another installation?

**Comment by javaboy79** [comment]
I am using a docker image as the install.  All other plugins seem to work fine.  When I activate this plugin I do see an error flash by.  I was able to capture it with a screenshot, which is difficult to post..  The pertinent information seems to be this line, indicating a permission issue.  I opened the permissions on the /var/www/plugins/rv_gmaps directory to 777 just to be sure and this error still occurs.

`Warning: fopen(./map.php): failed to open stream: Permission denied in /var/www/plugins/rv_gmaps/maintain.inc.php on line 41`

Oddly, most files here (/var/www) are owned by root, but the plugins have www-data ownership.  Is this normal?  Perhaps that is a clue.

**Comment by javaboy79** [comment]
In fact, opening permissions on the /var/www dir allowed this plugin to activate properly.  Perhaps this docker image non-standard.  I'm thinking all of these files should be owned by www-data.  Thoughts?

**Comment by natalijajuscenko** [comment]
Hello javaboy79,
I had the same problem with this plugin. I solved it just changing path to main map page. 
In file /plugins/rv_gmaps/include/functions.php in line 44 instead 
$url = get_root_url().'map';
I wrote
$url = get_root_url().'plugins/rv_gmaps/map';
Hope, it will help you :)

And a lot of thanks to modus75!!! Great plugin!!! I use it it in my project : http://kapai.briai.ku.lt/
