### ISSUE TITLE
Using RV Maps & Earth on Piwigo - get and error

### ISSUE THREAD

**Issue by designbysue** [Piwigo/piwigo-gmaps#3]
When I click the link to the Google Earth page from my gallery using piwigo I get the following message 
![screen shot 2017-03-28 at 9 15 11 am](https://cloud.githubusercontent.com/assets/26742060/24407249/77f5b372-1398-11e7-9e80-da627e6340cc.png)
followed by:
"Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details."
Can someone help me get this bug corrected?  Running the most current of all software. 
Gallery is at www.designbysue.com/photos
I am currently importing Gallery 3 so if you visit the site and don't see anything, please try again later.

Thanks
Sue

**Comment by modus75** [comment]
Invalid api key
DeletedApiProjectMapError

**Comment by designbysue** [comment]
Got it - for others the answer to the problem was found here 
http://stackoverflow.com/questions/38182710/google-maps-api-error-deletedapiprojectmaperror

"You should go to https://console.developers.google.com and after create your API KEY, go to "Google Maps JavaScript API" and just ENABLE (by default is DISABLE)"

Hint: after you create your API KEY - search within the Google Console for "Google Maps JavaScript API"  That took me directly to the page where I needed to enable as instructed.

Hopes this helps others with this issued.

Thanks for your reply modus75
Sue
