### ISSUE TITLE
Problem with all pictures taken in Australia

### ISSUE THREAD

**Issue by nikrol-mk** [Piwigo/piwigo-gmaps#5]
I can't see any pictures on the map taken in australia and singapore. Is it a Problem with GPS on the south hemisphere?

**Comment by modus75** [comment]
No. I have pictures in all 4 possible combinations of N/S E/W. 
Do you have a link to a photo page?

**Comment by nikrol-mk** [comment]
yes: 
http://www.mk-net.ch/piwigo/
Username: admin
Password: piwi2017

the same pictures with my "old software": 
http://www.mk-net.ch/reisereportagen/2017-australien/web/default/

Many thanks for your help

**Comment by modus75** [comment]
Your GPS exif does not follow standards. I looked at one photo and the GPS longitude ref tag is not E or W (piwigo core and not the plugin reads this data and ignores it)

**Comment by nikrol-mk** [comment]
You are right! Photoshop Elements Export jpg make my pictures broken. as tiff is it ok.
Many thanks for your help!!
regards
